### ISSUE TITLE
global error thrown

### ISSUE THREAD

**Issue by DesTincT** [crystalbit/node-sberbank-acquiring#10]
<img width="1299" alt="global error occured in get method" src="https://user-images.githubusercontent.com/1612160/223511320-b238285e-d241-4e48-acff-a89393125c7c.png">

global error thrown, even this is async function and should return resolve if order not found?

```
await acquiring.get(undefined, orderNumber);
```

**Comment by JoCat** [comment]
Since the query returns a non-zero error code, it is treated as an error in any case.

You can intercept the error in the request with try/catch and, in case of an error with an order not found, use resolve
for example:

```js
try {
  await acquiring.get(undefined, orderNumber);
} catch (error) {
  if (error.sberErrorCode == 6 /* or === '6' */) {
    return 'Order not found';
  }
  console.error('Error is caught:', error);
}
  ```
