### ISSUE TITLE
Предложения по проекту

### ISSUE THREAD

**Issue by JoCat** [crystalbit/node-sberbank-acquiring#6]
Привет, в первую очередь хочу поблагодарить за создание библиотеки, она сэкономила мне некоторое время для решения задач.

Сейчас я работаю в одной компании над проектом в котором используется эквайринг Сбербанка и у меня есть один вопрос к вам. Рассматриваете вы возможность внесения большого количества правок в библиотеку и добавления нового функционала?

На данный момент хотелось бы реализовать следующие вещи:

- Работа со связками (оплата, получение списка связок и их деактивация)
- Модифицировать некоторые запросы (напр. дополнить register передачей доп. параметров)
- Провести небольшой рефакторинг, возможно переписать библиотеку на Typescript
- Возможно что-то ещё

Имеет смысл мне развивать форк или же вы открыты к изменениям?

**Comment by crystalbit** [comment]
Добрый день! Спасибо взаимно, очень рад что помогло :)

Открыт к изменениям. По тому, что сам готов сделать - это перевести на тс и сделать рефакторинг. Писал это всё давно, и сам уже вижу некоторую необходимость.

Сам функционал менять не готов так как давно уже с эквайрингом не работал, и сейчас возврат к платёжной логике займёт у меня относительно много ресурсов.

Готов либо принимать регулярно пр либо добавить в репозиторий, чтобы всем делать меньше действий. Плюс тестовый аккаунт эквайринга, думаю, найду, так что базово протестировать тоже буду готов.

Если считаете более удобным форк, то тоже не проблема

**Comment by JoCat** [comment]
С добавлением в репозиторий было бы вообще отлично)

**Comment by crystalbit** [comment]
Доступ дал, закрываю ишью) Спасибо!
