### ISSUE TITLE
bindingType Typescript error

### ISSUE THREAD

**Issue by DesTincT** [crystalbit/node-sberbank-acquiring#9]
<img width="1323" alt="bindingType Typescript error" src="https://user-images.githubusercontent.com/1612160/223497690-d7d7a0cc-4526-4e57-a649-3a66be9b66f6.png">

- "typescript": "4.9.3"
- node: 14.18.1

**Comment by crystalbit** [comment]
@DesTincT thank you!
@JoCat thank you for the fix!
Merged, npmjs will be updated soon

**Comment by crystalbit** [comment]
1.2.1 published https://www.npmjs.com/package/sberbank-acquiring
